---
title: "Costa Rica: Estadísticas del comportamiento de los Casos de covid-19 para el viernes 22 de octubre del 2021"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
---

```{r setup, include=FALSE}
library(flexdashboard)

defaultEncoding <- "UTF8"
library(dplyr)
library(sf)
library(terra)
library(raster)
library(DT)
library(ggplot2)
library(plotly)
library(leaflet)
library(dygraphs)

```
```{r datos , warning=FALSE, message=FALSE}
casos <-
  st_read("/vsicurl/https://marcelocubero.github.io/capas_proyecto/casos.geojson",
          quiet = TRUE)
casos <-
  casos %>%
  st_transform(4326)

casos_ <-
  read.csv(file = "https://marcelocubero.github.io/capas_proyecto/casos_.csv",
           sep = ",",
           encoding = "UTF-8")


fallecidos <-
  rast("/vsicurl/https://marcelocubero.github.io/capas_proyecto/fallecidos.tif")

```

colum {data-width=350}
-----------------------------------------------------------------------

### Texto

### About dygraphs

This example makes use of the dygraphs R package. The dygraphs
package provides rich facilities for charting time-series data 
in R. You can use dygraphs at the R console, within R Markdown
documents, and within Shiny applications.

La [COVID-19](https://www.who.int/es/news-room/q-a-detail/coronavirus-disease-covid-19) es una enfermedad causada por un nuevo tipo de coronavirus conocido como SARS-CoV-2. 
Este virus fue reportado por vez primera el 31 de diciembre de 2019, en Wuhan (República Popular China), desde ese momento se han reportado 243,662,107 casos positivos de los cuales han fallecido 4.948.516 confirmados y entre 8 y 17 millones de personas estimadas.  
Según estadísticas de la *[Caja Costarricense del Seguro Social]* (https://www.ccss.sa.cr/web/coronavirus/), , en Costa Rica, se han reportado 553661 casos positivos de los cuales han fallecido 6880 personas, desde el primer caso reportado el 6 de marzo de 2020.  
En esta pagina web, se presentan datos, sobre la distribución del virus a nivel espacial en cuanto a los casos positivos, activos y fallecidos por cantón en Costa Rica.

```
Column {data-width=350}
-----------------------------------------------------------------------

### Casos activos y positivos por cantón y provincia

```{r}
casos_ %>%
  select(Cantón= canton,Provincia= provincia, Casos_Activos= activos, Casos_Positivos= positivos) %>%
datatable( casos_, options = list(
  language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json'),
  pageLength = 15
))
```

Casos positivos por cantón {data-orientation=rows}
===================================== 
Row {data-height=650}
-----------------------------------------------------------------------

### Casos positivos por cantón

```{r}
ggplot(casos_, aes(x= canton, y= positivos)) +
  geom_col( width = 0.5, fill= "Red") +
  ggtitle("Casos Positivos por cantón") +
  xlab("Cantón") +
  ylab("Cantidad de casos positivos") +
   theme(
    plot.title = element_text(size = 16, face = "bold"),
    text = element_text(size=8),
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)
  ) 
```

Casos activos por cantón {data-orientation=rows}
===================================== 
Row {data-height=650}
-----------------------------------------------------------------------
### Casos activos por cantón

```{r}
ggplot(casos_, aes(x= canton, y= activos)) +
  geom_col( width = 0.5, fill= "Brown") +
  ggtitle("Casos Activos por cantón") +
  xlab("Cantón") +
  ylab("Cantidad de casos activos") +
   theme(
    plot.title = element_text(size = 16, face = "bold"),
    text = element_text(size=8),
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)
  )
```
